### ISSUE TITLE
[REQUEST][WIP][PORT] After GG port is done, Add port for Master System!

### ISSUE THREAD

**Issue by TheRealHamtaro126** [OpenZoo/tinyzoo-gb#7]
Hello, Can you also add some work on a Master System port? It is where the Game Gear hardware came from, except for the Palette which is sort of similar to the EGA palette (64 colors), and the bigger screen size.

Can you support this system please?

**Comment by asiekierka** [comment]
At least with regards to my current rendering ideas, the system's limitations would make it prohibitively expensive to support the SMS due to its larger viewport.
